EarthquakeVisualization: config.hpp draw.hpp engine.hpp graphics.hpp quake.hpp camera.hpp earth.hpp main.cpp text.hpp
	g++ main.cpp -o EarthquakeVisualization `pkg-config --cflags --libs sdl2 glew` -I./

clean:
	rm EarthquakeVisualization
